//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 08:19:07 AM EDT 
//


package com.microsoft.schemas._2003._10.serialization.arrays;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.datacontract.schemas._2004._07.lciservicedatacontract.ArrayOfPostageCost;
import org.datacontract.schemas._2004._07.lciservicedatacontract.PostageDetails;


/**
 * <p>Java class for ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="KeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Key" type="{http://schemas.datacontract.org/2004/07/LCIServiceDataContract}PostageDetails"/&gt;
 *                   &lt;element name="Value" type="{http://schemas.datacontract.org/2004/07/LCIServiceDataContract}ArrayOfPostageCost"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk", propOrder = {
    "keyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk"
})
public class ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk {

    @XmlElement(name = "KeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk")
    protected List<ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk.KeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk> keyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk;

    /**
     * Gets the value of the keyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk.KeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk }
     * 
     * 
     */
    public List<ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk.KeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk> getKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk() {
        if (keyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk == null) {
            keyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk = new ArrayList<ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk.KeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk>();
        }
        return this.keyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Key" type="{http://schemas.datacontract.org/2004/07/LCIServiceDataContract}PostageDetails"/&gt;
     *         &lt;element name="Value" type="{http://schemas.datacontract.org/2004/07/LCIServiceDataContract}ArrayOfPostageCost"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "key",
        "value"
    })
    public static class KeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk {

        @XmlElement(name = "Key", required = true, nillable = true)
        protected PostageDetails key;
        @XmlElement(name = "Value", required = true, nillable = true)
        protected ArrayOfPostageCost value;

        /**
         * Gets the value of the key property.
         * 
         * @return
         *     possible object is
         *     {@link PostageDetails }
         *     
         */
        public PostageDetails getKey() {
            return key;
        }

        /**
         * Sets the value of the key property.
         * 
         * @param value
         *     allowed object is
         *     {@link PostageDetails }
         *     
         */
        public void setKey(PostageDetails value) {
            this.key = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link ArrayOfPostageCost }
         *     
         */
        public ArrayOfPostageCost getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link ArrayOfPostageCost }
         *     
         */
        public void setValue(ArrayOfPostageCost value) {
            this.value = value;
        }

    }

}
