//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 08:19:07 AM EDT 
//


package com.microsoft.schemas._2003._10.serialization.arrays;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.microsoft.schemas._2003._10.serialization.arrays package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/Arrays", "ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.microsoft.schemas._2003._10.serialization.arrays
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk }
     * 
     */
    public ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk createArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk() {
        return new ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk();
    }

    /**
     * Create an instance of {@link ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk.KeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk }
     * 
     */
    public ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk.KeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk createArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxkKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk() {
        return new ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk.KeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/Arrays", name = "ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk")
    public JAXBElement<ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk> createArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk(ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk value) {
        return new JAXBElement<ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk>(_ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk_QNAME, ArrayOfKeyValueOfPostageDetailsArrayOfPostageCoste2SJMIxk.class, null, value);
    }

}
